const tabelaTransicaoEstados = [
  /* 0  */ {
    D: 1,
    '"': 7,
    L: 9,
    "{": 10,
    eof: 12,
    "<": 13,
    ">": 16,
    "=": 18,
    "+": 19,
    "-": 19,
    "/": 19,
    "*": 19,
    "(": 20,
    ")": 21,
    ";": 22,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": 0,
    "\n": 0,
  },
  /* 1  */ {
    D: 1,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": 2,

    ".*": null,
    ".*": null,
    e: 4,
    E: 4,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 2  */ {
    D: 3,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 3  */ {
    D: 3,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: 4,
    E: 4,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 4  */ {
    D: 6,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": 5,
    "-": 5,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 5  */ {
    D: 6,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 6  */ {
    D: 6,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 7  */ {
    D: 7,
    '"': 8,
    L: 7,
    "{": 7,
    eof: null,
    "<": 7,
    ">": 7,
    "=": 7,
    "+": 7,
    "-": 7,
    "/": 7,
    "*": 7,
    "(": 7,
    ")": 7,
    ";": 7,
    ".": 7,
    ".*": 7,
    e: 7,
    E: 7,
    _: 7,
    "}": 7,
    " ": 7,
    "\n": null,
  },
  /* 8  */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 9  */ {
    D: 9,
    '"': null,
    L: 9,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: 9,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 10 */ {
    D: 10,
    '"': 10,
    L: 10,
    "{": 10,
    eof: null,
    "<": 10,
    ">": 10,
    "=": 10,
    "+": 10,
    "-": 10,
    "/": 10,
    "*": 10,
    "(": 10,
    ")": 10,
    ";": 10,
    ".": 10,
    ".*": 10,
    e: 10,
    E: 10,
    _: 10,
    "}": 11,
    " ": 10,
    "\n": null,
  },
  /* 11 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 12 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 13 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": 15,
    "=": 15,
    "+": null,
    "-": 14,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 14 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 15 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 16 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": 17,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 17 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 18 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 19 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 20 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 21 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 22 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
  /* 23 */ {
    D: null,
    '"': null,
    L: null,
    "{": null,
    eof: null,
    "<": null,
    ">": null,
    "=": null,
    "+": null,
    "-": null,
    "/": null,
    "*": null,
    "(": null,
    ")": null,
    ";": null,
    ".": null,
    ".*": null,
    e: null,
    E: null,
    _: null,
    "}": null,
    " ": null,
    "\n": null,
  },
];

const tabelaEstadosFinais = [
  { estado: 1, classe: "num" },
  { estado: 3, classe: "num" },
  { estado: 6, classe: "num" },
  { estado: 8, classe: "lit" },
  { estado: 9, classe: "id" },
  { estado: 11, classe: "comentario" },
  { estado: 12, classe: "eof" },
  { estado: 13, classe: "opr" },
  { estado: 14, classe: "rcb" },
  { estado: 15, classe: "opr" },
  { estado: 16, classe: "opr" },
  { estado: 17, classe: "opr" },
  { estado: 18, classe: "opr" },
  { estado: 19, classe: "opm" },
  { estado: 20, classe: "ab_p" },
  { estado: 21, classe: "fc_p" },
  { estado: 22, classe: "pt_v" },
];

const tabelaErrosPorEstado = [
  { estado: 0, mensagem: "Caracter não pertence ao alfabeto" },
  { estado: 2, mensagem: "Necessário digito após o ponto" },
  { estado: 4, mensagem: "Necessário dígito ou sinal após exponencial" },
  { estado: 5, mensagem: "Necessário digito após o sinal" },
  { estado: 7, mensagem: "Necessário fechar aspas" },
  { estado: 10, mensagem: "Necessário fechar chaves" },
  {
    estado: null,
    mensagem: "Caracter não leva a nenhum estado de transição",
  },
];

const tabelaSimbolos = [
  { classe: "inicio", lexema: "inicio", tipo: "inicio" },
  { classe: "varinicio", lexema: "varinicio", tipo: "varinicio" },
  { classe: "varfim", lexema: "varfim", tipo: "varfim" },
  { classe: "escreva", lexema: "escreva", tipo: "escreva" },
  { classe: "leia", lexema: "leia", tipo: "leia" },
  { classe: "se", lexema: "se", tipo: "se" },
  { classe: "entao", lexema: "entao", tipo: "entao" },
  { classe: "fimse", lexema: "fimse", tipo: "fimse" },
  { classe: "repita", lexema: "repita", tipo: "repita" },
  { classe: "fimrepita", lexema: "fimrepita", tipo: "fimrepita" },
  { classe: "fim", lexema: "fim", tipo: "fim" },
  { classe: "inteiro", lexema: "inteiro", tipo: "inteiro" },
  { classe: "literal", lexema: "literal", tipo: "literal" },
  { classe: "real", lexema: "real", tipo: "real" },
];

const chavesTabelaTransicao = [
  "D",
  '"',
  "L",
  "{",
  "eof",
  "<",
  ">",
  "=",
  "+",
  "-",
  "/",
  "*",
  "(",
  ")",
  ";",
  ".",
  "e",
  "E",
  "_",
  "}",
  " ",
  "\n",
];

const gramaticRules = {
  R1: {
    A: "S'",
    beta: "E",
  },
  R2: {
    A: "E",
    beta: "(T)",
  },
  R3: {
    A: "T",
    beta: "a",
  },
};

const actionSyntaticAnalyzer = {
  0: {
    ab_p: { id: "s", action: "S2", t: 2 },
  },
  1: {
    eof: { id: "acc", action: "Acc" },
  },
  2: {
    id: { id: "s", action: "S3", t: 3 },
  },
  3: {
    ab_p: { id: "r", action: "R3" },
    fc_p: { id: "r", action: "R3" },
    id: { id: "r", action: "R3" },
    eof: { id: "r", action: "R3" },
  },
  4: {
    fc_p: { id: "s", action: "S5", t: 5 },
  },
  5: {
    ab_p: { id: "r", action: "R2" },
    fc_p: { id: "r", action: "R2" },
    id: { id: "r", action: "R2" },
    eof: { id: "r", action: "R2" },
  },
};

const goToSyntaticAnalyzer = {
  0: {
    E: 1,
  },
  2: {
    T: 4,
  },
};

module.exports = {
  tabelaTransicaoEstados,
  tabelaSimbolos,
  tabelaEstadosFinais,
  tabelaErrosPorEstado,
  chavesTabelaTransicao,
  gramaticRules,
  actionSyntaticAnalyzer,
  goToSyntaticAnalyzer,
};
